### Numpy  is a package used to perform mathematicval operations

#### np.array is used to create a numpy array

In [19]:
import numpy as np
arr1=np.array([1,2,3,4])
print(arr1)
# printinng shape of an array
print(arr1.shape)
print(type(arr1))
arr3=np.array([[1,2,3,4],[4,5,6,7]])
print(arr3)
print(arr3.shape)


# using np.arange to create a nimpy array 
arr4=np.arange(0,10,2).reshape(5,1)
print(arr4)
print(arr4.shape)

[1 2 3 4]
(4,)
<class 'numpy.ndarray'>
[[1 2 3 4]
 [4 5 6 7]]
(2, 4)
[[0]
 [2]
 [4]
 [6]
 [8]]
(5, 1)


### Reshaping an array
#### Can only be reshaped in multiples , in case of 1D array , the number of  total elements should match 

In [11]:
arr2=arr1.reshape(2,2)
arr2

array([[1, 2],
       [3, 4]])

Creating a  unity matrix


In [21]:
uni=np.ones((3,4))
uni

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Creating an identity matrix

In [24]:
id_mat=np.eye(3)
id_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
arr4=np.array([[1,2,3,4],[4,5,6,7]])
print(f"Array:>{arr4}")
print(f"Shape:>{arr4.shape}")
print(F"dimensions:>{arr4.ndim}")
print(f"No of elements:>{arr4.size}")
print(f"Datatype of elements:>{arr4.dtype}")

Array:>[[1 2 3 4]
 [4 5 6 7]]
Shape:>(2, 4)
dimensions:>2
No of elements:>8
Datatype of elements:>int64


#### Numpy vectorised operations
##### Addition/Substraction/Multipication/Division

In [41]:
a1=np.arange(1,6)
a2=np.arange(10,15)
print(f"a1={a1}\na2={a2}")
print("*****************************************")
print(f"Addition --> {a1+a2}")
print("*****************************************")
print(f"Substraction --> {a1-a2}")
print("*****************************************")
print(f"Multipication --> {a1*a2}")
print("*****************************************")
print(f"Division --> {a1/a2}")


a1=[1 2 3 4 5]
a2=[10 11 12 13 14]
*****************************************
Addition --> [11 13 15 17 19]
*****************************************
Substraction --> [-9 -9 -9 -9 -9]
*****************************************
Multipication --> [10 22 36 52 70]
*****************************************
Division --> [0.1        0.18181818 0.25       0.30769231 0.35714286]


Universal functions


In [45]:
# sqrt
arr=[2,3,4,5,6]
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
